apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applicationsets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mgkaiser/ArgoApplications-KaiserGuru.git
    targetRevision: HEAD
    path: .
    directory:
      recurse: false
      include: '*applicationset.yaml'
  destination:
    name: "in-cluster"
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
