configData:
  storage:
    delete:
      enabled: true
extraEnvVars:
- name: OTEL_SDK_DISABLED
  value: "true"
- name: OTEL_TRACES_EXPORTER
  value: none
garbageCollect:
  enabled: true
ingress:
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
    cert-manager.io/issuer-kind: ClusterIssuer
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
  className: nginx
  enabled: true
  hosts:
  - registry.kaiser.guru
  labels: {}
  path: /
  tls:
  - hosts:
    - registry.kaiser.guru
    secretName: chart-example-tls
persistence:
  accessMode: ReadWriteOnce
  enabled: true
  size: 50Gi
  storageClass: nfs
secrets:
  htpasswd: mkaiser:$2y$05$BlXhOwiDpww0DWpK.tyaouciDpDCI.ztvKIKlqFfRBsKRzRF.ZboK
