mode: standalone
image:
  registry: bitnamilegacy
  repository: minio
  tag: 2025.7.23-debian-12-r3
global:
  security:
    allowInsecureImages: true
auth:
  rootUser: admin
  rootPassword: changeme
persistence:
  enabled: true
  size: 10Gi
service:
  type: ClusterIP
ingress:
  enabled: false
