mariadb:
    enabled: true
persistence:
    enabled: true
service:
    type: ClusterIP
ingress:
    enabled: true
    hostname: catkaiserart.kaiser.guru
    ingressClassName: nginx
    tls: true
    annotations:
        cert-manager.io/issuer: letsencrypt-prod
        cert-manager.io/issuer-kind: ClusterIssuer
        nginx.ingress.kubernetes.io/proxy-connect-timeout: '30'
        nginx.ingress.kubernetes.io/proxy-read-timeout: '1800'
        nginx.ingress.kubernetes.io/proxy-send-timeout: '1800'
wordpressBlogName: My WordPress
wordpressEmail: admin@example.com
wordpressPassword: changeme
wordpressUsername: admin
